<?php
/**
 * Created by PhpStorm.
 * User: ari
 * Date: 9/15/14
 * Time: 8:58 AM
 */
namespace Site\Account\Session\Exceptions;

use CPath\Request\Exceptions\RequestException;

class UserSessionNotFound extends RequestException
{
    function __construct($message, $statusCode = null, \Exception $previous = null) {
        parent::__construct($message, $statusCode, $previous); // TODO: Change the autogenerated stub
    }

}

