<?php
/**
 * Created by PhpStorm.
 * User: ari
 * Date: 11/18/14
 * Time: 9:23 AM
 */
namespace Site\Account\Session\Exceptions;

use CPath\Request\Exceptions\RequestException;

class UserSessionAlreadyExists extends RequestException
{
    function __construct($message, $statusCode = null, \Exception $previous = null) {
        parent::__construct($message, $statusCode, $previous); // TODO: Change the autogenerated stub
    }
}